steps:
# - name: 'gcr.io/cloud-builders/gsutil'
# args: ['cp', 'gs://sakuraba-sample-rails-sample/.env.production', '.']

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.production.enc
  - --plaintext-file=.env.production
  - --location=global
  - --keyring=builder-keyring
  - --key=builder-key
  
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/rails-docker-sample', '.' ]

images:
  - 'gcr.io/$PROJECT_ID/rails-docker-sample'
